version: "3.8"

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/lempstack
      - ./docker/nginx:/etc/nginx/conf.d

  php:
    image: php:7.4-fpm
    working_dir: /var/www/lempstack
    volumes:
      - ./src:/var/www/lempstack

